INSERT INTO CLIENT(NAME, LOGIN, PASSWORD) VALUES ('Thalyson','thalyson','123');
INSERT INTO STUDENT(PAID, REGISTRATION, CLIENT_ID) VALUES (0, '20220001', 1);

INSERT INTO CLIENT(NAME, LOGIN, PASSWORD) VALUES ('Saulo','saulo', '123');
INSERT INTO STUDENT(PAID, REGISTRATION, CLIENT_ID) VALUES (0, '20220002', 2);

INSERT INTO CLIENT(NAME, LOGIN, PASSWORD) VALUES ('Adriano', 'adriano', '123');
INSERT INTO STUDENT(PAID, REGISTRATION, CLIENT_ID) VALUES (0, '20220003', 3);

INSERT INTO BOX(CAPACITY, CREATE_BY, NAME) VALUES (30,'Thalyson','BinoBox');
INSERT INTO BOX(CAPACITY, CREATE_BY, NAME) VALUES (20,'Thalyson','BinoBox Fortaleza');
INSERT INTO BOX(CAPACITY, CREATE_BY, NAME) VALUES (50,'Saulo','SaBox');